[control]
# Disabling all steps makes running `dotfiles` a no-op. Each step can generally
# be configured via [step.<name>] and [step.<name>.<platform>].
steps = [
  # Prints a welcome message. Used for testing, does not affect behavior.
  "welcome",

  # Check that $PATH is setup.
  "path",

  # Check that certain fonts are installed.
  "fonts",

  "settings",
  "commands",
  "programs",
]

[control.mac]
# Disable specific steps for this platform.
disable_steps = [
  "welcome",
]

[step.settings.mac]
finder_show_extensions = true
finder_show_hidden_files = true
finder_warn_on_extension_change = false
spaces_rearrange_automatically = false
dock_orientation = "left"
dock_autohide = true


##### Old config #####

[common]
# Commands that are required. Installation fails quickly if any of these are
# not available or unable to be installed.
required_commands = [
  "sudo",
  "which",
]

# Desired commands. Installs using the current platforms `package_manager`.
commands = [
  "exa",
  "htop",
  "git",
  "cargo",
  "rustup",
  "fd",
  "ripgrep",
  "vim",
  "nvim",
  "nano",
  "tmux",
  "bat",
]

[arch]
package_manager = "yay"

[mac]
package_manager = "brew"

# Programs to setup. Each of these have custom handlers, this does not support
# any generic program. Installs where possible, otherwise warns when manual
# installation is needed.
programs = [
  "alacritty",
  "alfred",
  "alt-tab",
  "bitwarden",
  "chrome",
  "discord",
  "dropbox",
  "firefox",
  "karabiner",
  "sublime-text",
  "vscode",
  "xcode-command-line-tools",
]

# Settings to configure in MacOS.
settings = [
  "finder-always-show-hidden-files",
]
